language: node_js

node_js:
  - "10.10.0"

sudo: required

env:
  matrix:
    #- TASK="yarn test" remove comment when there is a test suite set
    - TASK="yarn lint"

before_script:
  - yarn install

script:
  - $TASK
