version: '3.5'

services:
  db:
    container_name: avaleasy-db
    image: mongo:3.2
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      - avaleasy-net

  api:
    container_name: avaleasy-backend
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - avaleasy-net
    depends_on:
      - db

networks:
  avaleasy-net:
    name: avaleasy-net

