version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start
    networks:
      - avaleasy-net
networks:
  avaleasy-net:
    external:
      name: avaleasy-net

